name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for better analysis
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    # Python Code Quality
    - name: Python - Install quality tools
      run: |
        pip install pylint mypy bandit black isort flake8 coverage
    
    - name: Python - Type checking with mypy
      run: |
        cd backend
        mypy app/ --ignore-missing-imports || true
    
    - name: Python - Security check with bandit
      run: |
        cd backend
        bandit -r app/ -f json -o bandit-report.json || true
    
    - name: Python - Complexity check
      run: |
        pip install radon
        cd backend
        radon cc app/ -a -nb || true
        radon mi app/ -nb || true
    
    # JavaScript/TypeScript Code Quality
    - name: Frontend - Install dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Frontend - ESLint
      run: |
        cd frontend
        npm run lint || true
    
    - name: Frontend - Type checking
      run: |
        cd frontend
        npx tsc --noEmit || true
    
    # SonarCloud Analysis (if configured)
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=quantum-trading-ai
          -Dsonar.organization=chandrashekargattu
          -Dsonar.sources=.
          -Dsonar.python.coverage.reportPaths=backend/coverage.xml
          -Dsonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
